### PR TITLE
feat: add initial milan support

### PR DESCRIPTION
**Pull request by haraldh**

### CODE REVIEW

**Comment by haraldh** [comment]
@connorkuehl : `tests/launch.rs` fails at  `launcher.inject(secret, address_space.addr()).unwrap();`

```
[pid 109001] ioctl(5, KVM_MEMORY_ENCRYPT_OP, 0x7f30ac4401e8) = -1 EIO (Input/output error)
```

**Comment by haraldh** [comment]
btw, an update sevctl returns:
```
     Running `target/debug/sevctl verify`
PDH EP384 D256 ab065efc0881d7fe902629a3d0a9278ad251f38945e1bc62b6e5f72029ce3a63
 ⬑ PEK EP384 E256 3766689294b55e6f5aa5e70114642ae7f5654291489ade7a280f25b69ed75c95
   •⬑ OCA EP384 E256 b464820036850844677dbd1739bb82a58e8d76025e149efe4cad2724f2b4cbab
    ⬑ CEK EP384 E256 7ec815c688649cc85c4fdcd712e14e6cf3a7854fac63b0fbf39c103660794e3d
       ⬑ ASK R4096 R384 95cba79ba3c77daea79f741bade8156a50b1c59f6d6fda104d16dd264729f5ee8989522f3711fc7c84719921ceb31bc0
         •⬑ ARK R4096 R384 569da618dfe64015c343db6d975e77b72fdeacd16edd02d9d09b889b8f0f1d91ffa5dfbd86f7ac574a1a7883b7a1e737
```

**Comment by haraldh** [comment]
ok, rome works with 5.12.14-300.fc34.x86_64 and fails with kernel-5.12.17-300.fc34.x86_64
also at KVM_SEV_LAUNCH_SECRET

**Comment by npmccallum** [comment]
@haraldh Do we care since we're dropping support for non-SNP?

**Comment by connorkuehl** [comment]
> @haraldh Do we care since we're dropping support for non-SNP?

In addition to this, shouldn't this go into enarx/snp?

**Comment by haraldh** [comment]
@connorkuehl normal SEV is also supposed to work on a milan machine?

**Comment by connorkuehl** [comment]
> @connorkuehl normal SEV is also supposed to work on a milan machine?

Yes, I agree the fix for SEV should merge here. But I would argue the Milan certificates should go into enarx/snp, which is similarly where we plan to upstream SNP ioctls.

**Comment by npmccallum** [comment]
There's two cases here:
1. Launching SEV or SEV-ES on Milan.
2. Launching SEV-SNP on Milan.

The certs will need to go here for the first case and in `snp` for the second case. So I'm in favor of merging them.

**Comment by connorkuehl** [comment]
> There's two cases here:
> 
>     1. Launching SEV or SEV-ES on Milan.
> 
>     2. Launching SEV-SNP on Milan.
> 
> 
> The certs will need to go here for the first case and in `snp` for the second case. So I'm in favor of merging them.

Ah, right, of course, that makes perfect sense, I wasn't considering that.

**Review by npmccallum — APPROVED** [review]

**Comment by npmccallum** [comment]
@connorkuehl Can you review?

**Review by connorkuehl — APPROVED** [review]

**Pull request merged**
