### PR TITLE
Enable modular test to check whether nightly features are enabled

### PR DESCRIPTION
**Pull request by mbestavros**
This enables the modular test action present in this repo: https://github.com/enarx/nightly-features

### CODE REVIEW

**Comment by npmccallum** [comment]
@mbestavros You can see the minimal supported Rust version for this crate here:
https://github.com/enarx/sev/blob/master/.github/workflows/test.yml#L24

Since this crate builds on stable and has no optional nightly features, it should not allow any nightly features.

**Review by npmccallum — CHANGES_REQUESTED** [review]
@mbestavros You can see the minimal supported Rust version for this crate here:
https://github.com/enarx/sev/blob/master/.github/workflows/test.yml#L24

Since this crate builds on stable and has no optional nightly features, it should not allow any nightly features.

Also, this should not get its own workflow file. It should be a job in the `lint.yml` workflow file.

**Review by connorkuehl — APPROVED** [review]
Thanks!

**Review by haraldh — APPROVED** [review]

**Comment by mbestavros** [comment]
We've decided we don't want to pursue this.

**Pull request closed without merging**
