### PR TITLE
Enable modular test to check whether SPDX headers are present

### PR DESCRIPTION
**Pull request by mbestavros**
This enables the modular test action present in this repo: https://github.com/enarx/spdx

### CODE REVIEW

**Review by lkatalin — DISMISSED** [review]

**Review by connorkuehl — CHANGES_REQUESTED** [review]
This would probably fit in nicely in with `.github/workflows/lint.yml` instead of being its own file.

**Comment by mbestavros** [comment]
@connorkuehl You are right. I've appended it to `lint.yml`.

**Review by connorkuehl — DISMISSED** [review]

**Review by haraldh — DISMISSED** [review]

**Comment by connorkuehl** [comment]
@mbestavros What's the status on this?

**Comment by mbestavros** [comment]
@connorkuehl The associated action needs some changes. While this will eventually happen, it won't be immediately.

**Review by haraldh — APPROVED** [review]

**Review by connorkuehl — CHANGES_REQUESTED** [review]
I'm not sure if the test is working. I've spot-checked 4 or 5 of the files that the logs say are missing an SPDX header and they do have an SPDX header.

I also believe each file has one:

```console
$ find src tests -name '*.rs' | xargs grep -L "SPDX-License-Identifier: Apache-2.0"
```

**Comment by mbestavros** [comment]
@connorkuehl You're right -- there was a bug. I've just fixed it.

**Review by connorkuehl — APPROVED** [review]

**Pull request merged**
